### ISSUE TITLE
Keycloak branch: UNKNOWN_CLIENT, client_id is null?

### ISSUE THREAD

**Issue by cornelius-agrippa** [FraunhoferIOSB/SensorThingsServer#11]
Hello,

First of all, thank you for providing a branch that supports keycloak out of the box. I'm pretty new to keycloak so please excuse my ignorance if this is a silly problem.

I've been trying to configure the application with my keycloak server, however I'm having some trouble accessing any routes after successfully logging in, getting http error 403 everytime along with the message: `Access to the specified resource has been forbidden.`

I'm running the SensorThings Server in Tomcat 8.0 (with Keycloak 3.1.0 adapters), so I checked the logs  to try and understand what went wrong. It seems to be generating the following message:
`ERROR:    {"error":"unauthorized_client","error_description":"UNKNOWN_CLIENT: Client was not identified by any client authenticator"}`

I've created a realm named `SensorThings` and a client in this realm named `SensorThingsService` and I thought maybe I set the client id wrong in my keycloak.json, which looks like this:
```
{
  "realm" : "SensorThings",
  "resource" : "SensorThingsService",
  "auth-server-url" : "http://<My Keycloak Service>:8081/auth",
  "ssl-required" : "none",
  "use-resource-role-mappings" : false,
  "enable-cors" : true,
  "cors-max-age" : 1000,
  "cors-allowed-methods" : "POST, PUT, DELETE, GET",
  "bearer-only" : false,
  "enable-basic-auth" : false,
  "expose-token" : true,
  "connection-pool-size" : 20,
  "disable-trust-manager": false,
  "allow-any-hostname" : false,
  "token-minimum-time-to-live" : 10,
  "min-time-between-jwks-requests" : 10,
  "public-key-cache-ttl": 86400
}
```

Does everything look ok in my keycloak.json?

I then checked the Keycloak's server log and for some reason the client id seems to be arriving as null everytime I make a request:
```
11:26:56,953 WARN  [org.keycloak.events] (default task-9) type=CODE_TO_TOKEN_ERROR, realmId=SensorThings, clientId=null, userId=null, ipAddress=<My IP address>, error=invalid_client_credentials, grant_type=authorization_code
```
I figure this is why tomcat is telling me "Client was not identified". But what could be causing this? Again, please excuse if this is a silly issue :)

My best regards

**Comment by hylkevds** [comment]
I'm fairly new to Keycloak myself :)
I'll have another look at it tomorrow.

**Comment by cornelius-agrippa** [comment]
Hello Hylke, thank you :)

I think I found out why: I was missing the attribute `"public-client": true`  in my `keycloak.json`, and now keycloak seems to accept the service :). It's documented here: https://keycloak.gitbooks.io/documentation/securing_apps/topics/oidc/java/java-adapter-config.html

I'm getting a 404 error trying to access any routes in /v1.0 and /DatabaseStatus, however. Though this is likely a problem on my side which I'll check ASAP.

**Comment by hylkevds** [comment]
Did you generate the json config yourself, or did you let Keycloak generate it for you? I think I used the Keycloak generated one, but mine did also have a credentials section with a secret in it.

I also used `"use-resource-role-mappings": true` so I could set the access rights for read/create/update/delete/admin from Keycloak:

```
{
  "realm": "sensorThings",
  "auth-server-url": "http://localhost:8180/auth",
  "ssl-required": "external",
  "resource": "SensorThingsDevelop",
  "credentials": {
    "secret": "xxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  },
  "use-resource-role-mappings": true
}
```

**Comment by cornelius-agrippa** [comment]
I did write the json myself based on the link I posted before. Generating through Keycloak gives me a json similar to yours, which works just fine too! Though I needed to change the `Access Type` to `confidential` on the client's configuration page.

I'm not sure if I understand `use-resource-role-mappings` too well yet. It seems to gather the roles based on either the realm of the application, right? I defined the roles realm-wise at the moment.

Thanks for your help so far :)

**Comment by cornelius-agrippa** [comment]
Forgive my double post. I wasn't sure where to ask this or if I should open a new issue.

Have you ever configured your Access Type in keycloak as Bearer-Only (only allow access to the API if the Authorization header is present and the client is the bearer of a valid access-token)?

Sadly I'm having some trouble with it. I'm trying to reach the API through an AJAX client but I keep getting the error: `XMLHttpRequest cannot load http://localhost:8080/sensorthings/v1.0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 403.`.

In the WEB-INF/web.xml of the SensorThingsServer i tried adding the following to the CorsFilter:
```
<init-param>
    <param-name>cors.allowed.headers</param-name>
    <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers</param-value>
</init-param>
<init-param>
    <param-name>cors.exposed.headers</param-name>
    <param-value>Access-Control-Allow-Origin,Access-Control-Allow-Credentials</param-value>
</init-param>
```
But it didn't help. I also tried adding `"enable-cors": true` to SensorThingsServer's keycloak.json but sadly, to no avail.

Have you ever had an issue with this?

**Comment by hylkevds** [comment]
I've had to add the cors filter settings to the tomcat global web.xml. If they where in the application web.xml they would not work for me.

I also noticed that the security constraints needed some improvements, so I've updated those in the keycloak branch.

After that it worked.

**Comment by cornelius-agrippa** [comment]
Indeed applying CORS settings in the global settings worked perfectly.

Thank you for the update as well 👍
