### ISSUE TITLE
Time filters treated as text

### ISSUE THREAD

**Issue by aditisg17** [FraunhoferIOSB/SensorThingsServer#13]
A filter on time in API calls gives wrong result, as the resultant query takes time as "text" instead of "date"

**API Call :**
http://localhost:8080/SensorThingsService/v1.0/HistoricalLocations?$filter=(time ge '2017-05-19T10:10:27' and time le '2017-05-19T10:10:28') 

Resultant PostgreSQL query: 
select "e1"."ID", "e1"."ID", "e1"."TIME", "e1"."THING_ID"
from "HIST_LOCATIONS" "e1"
**where "e1"."TIME"::text >= ? and "e1"."TIME"::text <= ?**
order by "e1"."ID" asc

![historicallocation_datetimequery_issue](https://cloud.githubusercontent.com/assets/5745667/26241071/fbe2132e-3cb5-11e7-9471-03b32162eefd.png)

**Comment by hylkevds** [comment]
Dates in the URL must not be quoted as strings. If you quote them as string, they will be treated as strings.

`
v1.0/HistoricalLocations?$filter=(time ge 2017-05-19T10:10:27Z and time le 2017-05-19T10:10:28Z)
`

Don't forget to add the timezone and urlencode!
