### ISSUE TITLE
documentation to start the server

### ISSUE THREAD

**Issue by YimengZhu** [FraunhoferIOSB/SensorThingsServer#14]
Hi, do you have a more detailed instruction to start the server? I followed the one in the Read Me and I built the war successfully. (However I didn't configure the database as it mentioned at the beginning, it was too crude to understand...)

Then I'm confused that how can I start the server. As I go to http://localhost:8080/SensorThingsService/DatabaseStatus there is no server started...

Thank you

**Comment by hylkevds** [comment]
You have to deploy the war file in an Apache Tomcat server. Do you have Tomcat installed and running?

**Comment by YimengZhu** [comment]
I just copied the war file generated by running mvn install into the webapp folder. Then I went to http://localhost:8080 the console told me 
Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by hylkevds** [comment]
Did you start Tomcat?
Did you allow Tomcat in your firewall?
At the least you should see the Tomcat default page.
