### ISSUE TITLE
Unable to POST Things to the SensorThingsServer

### ISSUE THREAD

**Issue by tobi238** [FraunhoferIOSB/SensorThingsServer#15]
Hi,
I followed the installation instructions and successfully built the war file and installed it in Apache Tomcat.
I can now access the API at http://localhost:8080/SensorThingsServer-1.0/ but I'm not able to insert data.

I'm using Postman to perform a POST to http://localhost:8080/SensorThingsServer-1.0/v1.0/Things with the following text body as application/json:
```javascript
{
  "description": "Weather Station",
  "properties": {
    "name": "test a",
    "type": "abc"
  },
  "Locations": [
    {
      "encodingType": "application/vnd.geo+json",
      "description": "Weather Station",
      "location": {"coordinates":[-18.1002,65.6856],"type":"Point"}
    }
  ]
}
```
The Server responds with 403 Forbidden. What am I doing wrong?

Many thanks in advance,
Tobias

**Comment by hylkevds** [comment]
That JSON should give you a 400 bad request with the message `Missing required property 'name'`
How exactly are you making the post?

The server itself never generates a 403, so it's either something in your Tomcat configuration rejecting the post, or your browser rejecting it due to cross-site-scripting restrictions. I've seen the latter happen when using chrome's Advanced Rest Client from inside the browser, instead of the stand-alone version.

**Comment by tobi238** [comment]
OK, it seems to be a Tomcat config issue: I just tested an AJAX POST Request from an HTML File on the same (Tomcat) Server and it works!

So now I just need to figure out how to change the CORS settings for Tomcat so I can access the server from somewhere else... But no success so far 😫

Thanks for your fast reply 👍

**Comment by hylkevds** [comment]
In issue #11 we found out that the cors settings sometimes need to be in the global web.xml of Tomcat for them to work. So if you have issues getting cors to work, try that.

**Comment by tobi238** [comment]
Ok, I followed issue #11  and added the CORS settings to the SensorThingsServer\Web-INF\web.xml file AND the global CATALINA_HOME\conf\web.xml file:

```xml
<filter>
  <filter-name>CorsFilter</filter-name>
  <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
  <init-param>
    <param-name>cors.allowed.origins</param-name>
    <param-value>http://localhost:80, http://localhost:8080, http://localhost:81, http://localhost:8100</param-value>
  </init-param>
  <init-param>
    <param-name>cors.allowed.methods</param-name>
    <param-value>GET,POST,HEAD,OPTIONS</param-value>
  </init-param>
  <init-param>
    <param-name>cors.support.credentials</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>
    <param-name>cors.allowed.headers</param-name>
    <param-value>Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization</param-value>
  </init-param>
</filter>

<filter-mapping>
  <filter-name>CorsFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
```

Now it's working, thank you very much 😃
