### ISSUE TITLE
Add change log for future releases

### ISSUE THREAD

**Issue by selimnairb** [FraunhoferIOSB/SensorThingsServer#20]
Version 1.1 was released last week.  However, I don't see a change log documenting what has changed.  One way to do this might be to handle releases using feature and develop branches.  The change log can be updated for each feature branch; feature branches could be merged into develop when they are complete.  Then, when develop is merged into master for a release, the change log will automatically contain all changes in the release (though it may need to be updated to collect all changes into the specific number of the next release).  Happy to help in any way I can.

**Comment by hylkevds** [comment]
You're right, we should make a changelog file.
As a start we can probably generate one from the GIT log and then clean that up...

**Comment by hylkevds** [comment]
I've added a changelog:
https://github.com/FraunhoferIOSB/SensorThingsServer/blob/master/CHANGELOG.md
