### ISSUE TITLE
Location encodingType - GeoJSON "application/geo+json" media type support

### ISSUE THREAD

**Issue by sudhamani1983** [FraunhoferIOSB/SensorThingsServer#21]
Encoding type GeoJSON with "application/geo+json" media type not inserting **geometry** value in "LOCATIONS" table GEOM column . But media type "application/vnd.geo+json" is working fine.

I checked RFC specs (  **https://tools.ietf.org/html/rfc7946** ) for GeoJSON, seems like media type "application/geo+json" is newer one.  The vnd one is older and obsolete.

Example : 
I have inserted two "Location" entity using different GeoJSON media Type. 

Dolce&Gabbana - "application/geo+json"
Sephora              - "application/vnd.geo+json"
Moncler              - "application/vnd.geo+json"

geometry value not inserted for **Dolce&Gabbana**

![image](https://user-images.githubusercontent.com/29911144/31752576-395f5bf0-b4be-11e7-829e-4f1feb972c45.png)

**Comment by hylkevds** [comment]
Thanks for the pointer. I've added the newer "application/geo+json" in 707a35dc19c602bccd09ccf496c3bcd50471befa

**Comment by sudhamani1983** [comment]
Tested and working fine. Thank you for your support
