### ISSUE TITLE
Do we have support to filter properties from Location GeoJSON with type 'Feature'

### ISSUE THREAD

**Issue by sudhamani1983** [FraunhoferIOSB/SensorThingsServer#28]
Is STA has support to filter properties of 'location' with type 'Feature'. Below is our sample Location data with type 'Feature'

**Sample Location :** 
{
     "name": "TestLocation",
      "encodingType": "application/geo+json",
      "description": "TestLocation",
      "location": {
      	"type": "Feature",
		  "geometry": {
		    "type": "Point",
		    "coordinates": [103.83170798,1.30438905]
		  },
		  "properties": {		   
		    "priority": "3"
		  }
      }    
    }

I am trying to filter Location by properties 'priority'. 

**Request :** 
http://localhost:8080/SensorThingsService/v1.0/Locations?$select=location&$filter=location/properties/priority eq '3'

**Error Message :** 
Failed to parse because (Set loglevel to trace for stack): Entity property location does not have custom properties (properties).

**Comment by hylkevds** [comment]
Currently that doesn't work (as you noticed) but it should be relatively easy to enable.

**Comment by hylkevds** [comment]
Should work in the latest version.

**Comment by sudhamani1983** [comment]
Thank you for your support.
