### ISSUE TITLE
why response is empty in ajax post?

### ISSUE THREAD

**Issue by moksnow** [FraunhoferIOSB/SensorThingsServer#33]
i have a problem, when i post a things entity or others entity by jquery ajax, in success function my result is empty.

> $.ajax({
>     url: "http://localhost:8099/SensorThingsService/v1.0/Things",
>     type: "POST",
>     data: json,
>     contentType: "application/json; charset=utf-8",
>     success: function(result){	
>        alert(JSON.stringify(result));
>     },
>     error: function(response, status){
>         console.log(status);
>     }
> });

line 230  " response.setResult((T) entity); "  in service.java class fill exactly true but in client response not showing anything. what is problem?

**Comment by hylkevds** [comment]
The result of a POST is always empty, see #24 
You have to use the Location header that is returned.
