### ISSUE TITLE
Connection via websockest with MQTT.js

### ISSUE THREAD

**Issue by Sven1113** [FraunhoferIOSB/SensorThingsServer#36]
Hi, I try to connect with MQTT.js package via websockets

My code:
var mqtt = require("mqtt"),
      options = {
          port: 9876,
          keepalive: 60,
          encoding: "utf8",
          protocol: "ws",
     },
    client  = mqtt.connect("http://mySensorThingsIP", options);

With the protocol: "mqtt" and the port: 1883 I get a connection, but it does not work over websockets. What's my mistake?

I need the connection via Websockets because I want to connect with extension-package: "browserMqtt" for MQTT.js directly in browser to the SensorThings-Server. This works only with a websocket-connection and not with a direct connection via protocol: "mqtt and port: 1883.

I tried the follow possibilities:

var client = mqtt.connect("ws://mySensorThingsIP:9876/mqtt");
var client = mqtt.connect({host: "mySensorThingsIP", port : 9876, path : "/mqtt"});
var client = mqtt.connect({host: "mySensorThingsIP", port : 9876});

but i get this error message for all variants:
WebSocket connection to 'ws://mySensorThingsIP:9876/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by hylkevds** [comment]
When I try it on your server (you might want to edit out the IP address from your message) I also get the same error. I've tried it with the HiveMQ Websocket demo client: http://www.hivemq.com/demos/websocket-client/

However, I can connect to my local server with no problems, using: ws://localhost:9876/mqtt
Are you sure you don't have a firewall or reverse proxy in front of the server that blocks port 9876?

**Comment by Sven1113** [comment]
Thank's, the port was blocked.
