### ISSUE TITLE
Support building on Java 9

### ISSUE THREAD

**Issue by abourdon** [FraunhoferIOSB/SensorThingsServer#37]
Hi,

I'm unable to build the 1.3 version (and the SNAPSHOT version as well). Indeed, there are test failures during the Maven installation:

<img width="1215" alt="screen shot 2018-01-26 at 11 51 21" src="https://user-images.githubusercontent.com/1511715/35436579-463724e2-028f-11e8-97fb-97d6544dc0c9.png">

Steps to reproduce are the same as those explained from the README:
1. Clone repository
2. Run `git submodule init`
3. Run `git submodule update`
4. Run `mvn [clean] install`

Aurélien

**Comment by hylkevds** [comment]
I've just removed the codegen submodule from the source, since it is now available in the maven repository. Can you try again?

If it still doesn't work, please copy-paste the entire build log, since the final summary isn't very useful for determining what is going wrong.

**Comment by abourdon** [comment]
Hi,

The `SensorThingsServer.Core` module is now building fine, but there is still a (little) error from the `SensorThingsServer.SQL.PGLong` module. Javadoc generation fails:

<img width="1609" alt="screen shot 2018-01-26 at 12 27 55" src="https://user-images.githubusercontent.com/1511715/35437819-5e44a23a-0294-11e8-97a1-48d4014a78e6.png">

I attached the full log [here](https://github.com/FraunhoferIOSB/SensorThingsServer/files/1667581/build.txt).

Note I'm not interested to the project's Javadoc so I can skip it by using `mvn clean install -Dmaven.javadoc.skip=true` and then the build goes well.

**Comment by hylkevds** [comment]
Which java version are you using?

**Comment by abourdon** [comment]
1.9. I've just test with 1.8 and generation goes well.

**Comment by hylkevds** [comment]
Thanks, I've renamed this issue to specify we need to look at java 9.

**Comment by abourdon** [comment]
Ok, thanks for the support!

**Comment by ManfredSchenkIOSB** [comment]
https://stackoverflow.com/questions/47011019/java-9-migration-javax-annotation

**Comment by hylkevds** [comment]
The latest version should also build on Java 9. I've not tested running on Java 9 yet.

**Comment by abourdon** [comment]
I've just tested and it looks fine. I can close it now.
