### ISSUE TITLE
Publish Docker image to the public Docker hub

### ISSUE THREAD

**Issue by abourdon** [FraunhoferIOSB/SensorThingsServer#38]
Hi,

I would like to use the SensorThingsServer through its Docker image without be forced to create it from sources, but by pulling it from an official SensorThings' Docker repository (by using the [public Docker hub](https://hub.docker.com/) for instance).

Indeed, currently we have to:
1. Clone project's sources
2. Build project's sources
3. Use the existing Dockerfile that copies the generated war file from 2.

Actually this workflow works fine for SensorThingsServer's developers but not for users. Indeed, users would like to you image without being forced to create it.

Aurélien

**Comment by hylkevds** [comment]
Thank you for the suggestion, we're looking into it.

**Comment by phertweck** [comment]
@abourdon: We integrated 95d24f1 an automated build for Docker images. They will be pushed into our [Docker hub repository](https://hub.docker.com/r/fraunhoferiosb/sensorthingsserver/).
The docker-compose file will use those image, so users don't need to build the server.
