### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by abourdon** [FraunhoferIOSB/SensorThingsServer#41]
Hi,

Could it be possible to generate a new stable release that integrates latest changes (#37, #38)?

This way we could use a stable Docker image (i.e., linked to this stable version). Indeed, there is only a snapshot version in the Docker repository.

Thanks,
Aurélien

**Comment by phertweck** [comment]
Hi @abourdon,

we released a new version (v1.4) which also is available as tagged docker image on docker hub.

**Comment by abourdon** [comment]
Thank you @phertweck!
